
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true