
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/spring-main-guide
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 12345678

  jpa:
    database: mysql
    hibernate:
      dialect: "org.hibernate.dialect.MySQL5Dialect"
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true