spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/spring-main-guide
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 12345678

  jpa:
    database: mysql
    hibernate:
      dialect: "org.hibernate.dialect.MySQL5Dialect"
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
  paths-to-match:
    - /**