version: "3.8"
services:
  mariadb:
    container_name: mariadb
    image: "mariadb:latest"
    restart: always
    volumes:
      - db:/data/db
    env_file:
      - ./db/.env
    ports:
      - "3306:3306"
volumes:
  db:
